-- ==========================================================
-- Project: Oracle Cloud-Based Business Process & Reporting Automation Platform
-- File: 01_schema.sql
-- Purpose: Creates core tables for process tracking, approvals, KPI reporting, and audit history.
-- ==========================================================

CREATE TABLE app_users (
    user_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name      VARCHAR2(100) NOT NULL,
    email          VARCHAR2(150) UNIQUE NOT NULL,
    user_role      VARCHAR2(50) CHECK (user_role IN ('REQUESTOR', 'APPROVER', 'ADMIN', 'ANALYST')),
    department     VARCHAR2(80),
    created_at     DATE DEFAULT SYSDATE
);

CREATE TABLE business_process_requests (
    request_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_title   VARCHAR2(200) NOT NULL,
    request_type    VARCHAR2(80) NOT NULL,
    requestor_id    NUMBER NOT NULL,
    priority        VARCHAR2(20) CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    status          VARCHAR2(30) DEFAULT 'SUBMITTED'
                    CHECK (status IN ('SUBMITTED', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'COMPLETED')),
    submitted_date  DATE DEFAULT SYSDATE,
    completed_date  DATE,
    business_impact VARCHAR2(500),
    CONSTRAINT fk_process_requestor
        FOREIGN KEY (requestor_id) REFERENCES app_users(user_id)
);

CREATE TABLE approval_history (
    approval_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id      NUMBER NOT NULL,
    approver_id     NUMBER NOT NULL,
    approval_status VARCHAR2(30) CHECK (approval_status IN ('PENDING', 'APPROVED', 'REJECTED')),
    comments        VARCHAR2(500),
    action_date     DATE DEFAULT SYSDATE,
    CONSTRAINT fk_approval_request
        FOREIGN KEY (request_id) REFERENCES business_process_requests(request_id),
    CONSTRAINT fk_approval_approver
        FOREIGN KEY (approver_id) REFERENCES app_users(user_id)
);

CREATE TABLE process_kpi_metrics (
    metric_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id      NUMBER NOT NULL,
    cycle_time_days NUMBER,
    sla_status      VARCHAR2(30) CHECK (sla_status IN ('WITHIN_SLA', 'BREACHED', 'PENDING')),
    report_period   VARCHAR2(20),
    created_at      DATE DEFAULT SYSDATE,
    CONSTRAINT fk_kpi_request
        FOREIGN KEY (request_id) REFERENCES business_process_requests(request_id)
);
